Fix tè le
liguqu1997/software-modeling-frontend pull request #4
Opened 2018-11-19 19:02 UTC by liguqu1997

2018-11-20 03:39 UTC, thangvo38 requested changes
@liguqu1997 Minor changes. Sửa xong merge vào dev

2018-11-20 03:39 UTC, thangvo38 commented on ShoppingCart/src/app/shared/product-card/product-card.component.html
>      <p class="card-text">{{product.description}}
Description tối đa rất nhiều kí tự. Nên wrap text lại chỗ này.

2018-11-20 03:39 UTC, thangvo38 commented on ShoppingCart/src/app/shared/product-card/product-card.component.html
>      <h5 class="card-title">{{product.name}}</h5>
Name tối đa tới 252 kí tự. Nên wrap text lại chỗ này.

2018-11-21 03:24 UTC, lamqquyen commented
@thangvo38 check please

2018-11-21 03:27 UTC, thangvo38 commented
LGTM

2018-11-21 03:31 UTC, liguqu1997 commented on ShoppingCart/src/app/shared/product-card/product-card.component.html
>      <h5 class="card-title">{{product.name}}</h5>
name để show 30 ký tự thôi quá

2018-11-21 03:34 UTC, thangvo38 commented on ShoppingCart/src/app/shared/product-card/product-card.component.html
>      <h5 class="card-title">{{product.name}}</h5>
v thì 20-25 th

2018-11-21 03:36 UTC, merged